// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using A3_HT3610.Data;

namespace A3_HT3610.Migrations
{
    [DbContext(typeof(AuditContext))]
    [Migration("20211116104653_AuditsContext")]
    partial class AuditsContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("A3_HT3610.Models.Audit", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("AuditTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.HasIndex("AuditTypeId");

                    b.ToTable("Audit");

                    b.HasData(
                        new
                        {
                            AuditId = 1,
                            Amount = 5000.0,
                            AuditTypeId = 1,
                            CreatedDate = new DateTime(2021, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlayerName = "Bart"
                        },
                        new
                        {
                            AuditId = 2,
                            Amount = 2000.0,
                            AuditTypeId = 2,
                            CreatedDate = new DateTime(2021, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlayerName = "Bart"
                        },
                        new
                        {
                            AuditId = 3,
                            Amount = 2000.0,
                            AuditTypeId = 3,
                            CreatedDate = new DateTime(2021, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlayerName = "Bart"
                        },
                        new
                        {
                            AuditId = 4,
                            Amount = 1000.0,
                            AuditTypeId = 1,
                            CreatedDate = new DateTime(2021, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlayerName = "Brian"
                        },
                        new
                        {
                            AuditId = 5,
                            Amount = 0.0,
                            AuditTypeId = 4,
                            CreatedDate = new DateTime(2021, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlayerName = "Brian"
                        });
                });

            modelBuilder.Entity("A3_HT3610.Models.AuditType", b =>
                {
                    b.Property<int>("AuditTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditTypeId");

                    b.ToTable("AuditType");

                    b.HasData(
                        new
                        {
                            AuditTypeId = 1,
                            Name = "Cash In"
                        },
                        new
                        {
                            AuditTypeId = 2,
                            Name = "Cash Out"
                        },
                        new
                        {
                            AuditTypeId = 3,
                            Name = "Win"
                        },
                        new
                        {
                            AuditTypeId = 4,
                            Name = "Lose"
                        });
                });

            modelBuilder.Entity("A3_HT3610.Models.Audit", b =>
                {
                    b.HasOne("A3_HT3610.Models.AuditType", "AuditType")
                        .WithMany()
                        .HasForeignKey("AuditTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditType");
                });
#pragma warning restore 612, 618
        }
    }
}
